"""Hub-safe defaults generated from configs/Default.yaml.

Do not edit this file by hand. Regenerate it with:

    python scripts/GenerateHubDriveSmokeRuntime.py

The real estimator, controller, safety monitor, state, and unit conversions
come from the normal ``LegoBalance`` modules. This module only carries a
small Pybricks-friendly config object because the hub cannot parse YAML.
"""


class ChassisConfig:
    def __init__(self):
        self.wheelRadius = 0.0285
        self.wheelBase = 0.11
        self.bodyMass = 0.276
        self.bodyHeightCoM = 0.105
        self.bodyInertia = 0.00337


class MotorsConfig:
    def __init__(self):
        self.leftPort = 'B'
        self.rightPort = 'F'
        self.maxAngularRate = 17.4532925199
        self.maxDuty = 90.0
        self.encoderCountsPerRev = 360
        self.forwardSign = -1
        self.leftEncoderSign = 1
        self.rightEncoderSign = -1


class ImuConfig:
    def __init__(self):
        self.tiltAxis = 'roll'
        self.tiltSign = 1
        self.zeroOffset = -0.025220008
        self.gyroBias = 0.0


class EstimatorConfig:
    def __init__(self):
        self.filterType = 'complementary'
        self.alpha = 0.98
        self.loopRate = 100.0


class ControlConfig:
    def __init__(self):
        self.loopRate = 100.0
        self.maxTilt = 2.0
        self.maxTiltRate = 10.0
        self.maxWheelRate = 17.44
        self.watchdogTimeout = 0.2
        self.targetTilt = -0.04


class ControllerConfig:
    def __init__(self):
        self.algorithm = 'nonlinear'
        self.gravityCompGain = 0.5
        self.kTheta = 250.0
        self.kThetaDot = 25.0
        self.kPhi = 0.0
        self.kPhiDot = 0.0
        self.sScale = 20.0
        self.actuatorTau = 0.25
        self.thetaDotFilterAlpha = 0.0
        self.thetaDeadband = 0.0
        self.thetaDotDeadband = 0.0
        self.pidKp = 200.0
        self.pidKi = 5.0
        self.pidKd = 80.0
        self.pidKs = -0.6
        self.pidIntegralStep = 0.25
        self.pidIntegralLimit = 50.0
        self.pidPositionTargetDeg = 0.0


class DriveConfig:
    def __init__(self):
        self.loopPeriodMs = 20
        self.printEveryN = 10
        self.stopDurationMs = 50
        self.driveDurationMs = 5000
        self.testSpeed = 17.44
        self.maxTiltForMotion = 0.8726646259971648


class LoggingConfig:
    def __init__(self):
        self.enabled = True
        self.level = 'info'
        self.bufferSize = 2048


class RobotConfig:
    def __init__(self):
        self.name = 'LegoBalance Mk1'
        self.description = 'Two wheel self balancing inverted pendulum on LEGO SPIKE Prime.'
        self.chassis = ChassisConfig()
        self.motors = MotorsConfig()
        self.imu = ImuConfig()
        self.estimator = EstimatorConfig()
        self.control = ControlConfig()
        self.controller = ControllerConfig()
        self.drive = DriveConfig()
        self.logging = LoggingConfig()


def DefaultConfig():
    return RobotConfig()
