"""Generate the hub-safe package-runtime config from configs/Default.yaml.

The SPIKE hub cannot parse YAML, so the package-backed hub entrypoints import
``LegoBalance.HubDriveSmokeRuntime`` instead. This script keeps that tiny
MicroPython-safe config module generated from the real desktop config so the
hub-side package runs follow the values set in YAML.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

DEFAULT_OUTPUT_PATH = SRC_ROOT / "LegoBalance" / "HubDriveSmokeRuntime.py"


def _Relative(path: Path) -> Path:
    try:
        return path.relative_to(REPO_ROOT)
    except ValueError:
        return path


def _FmtString(value: str) -> str:
    return repr(str(value))


def _FmtFloat(value: float) -> str:
    return repr(float(value))


def ValidateAgainstVerifiedDriveSmoke(config) -> None:
    """Compatibility shim.

    The package runtime now trusts the values loaded from
    ``configs/Default.yaml``. Validation of types and basic ranges happens in
    ``LegoBalance.RobotConfig``.
    """
    _ = config


def RenderHubDriveSmokeRuntime(config, config_path: Path) -> str:
    relative_config = _Relative(config_path)
    return f'''"""Hub-safe defaults generated from {relative_config}.

Do not edit this file by hand. Regenerate it with:

    python scripts/GenerateHubDriveSmokeRuntime.py

The real estimator, controller, safety monitor, state, and unit conversions
come from the normal ``LegoBalance`` modules. This module only carries a
small Pybricks-friendly config object because the hub cannot parse YAML.
"""


class ChassisConfig:
    def __init__(self):
        self.wheelRadius = {_FmtFloat(config.chassis.wheelRadius)}
        self.wheelBase = {_FmtFloat(config.chassis.wheelBase)}
        self.bodyMass = {_FmtFloat(config.chassis.bodyMass)}
        self.bodyHeightCoM = {_FmtFloat(config.chassis.bodyHeightCoM)}
        self.bodyInertia = {_FmtFloat(config.chassis.bodyInertia)}
        self.bodyLength = {_FmtFloat(config.chassis.bodyLength)}
        self.bodyHeight = {_FmtFloat(config.chassis.bodyHeight)}


class MotorsConfig:
    def __init__(self):
        self.leftPort = {_FmtString(config.motors.leftPort)}
        self.rightPort = {_FmtString(config.motors.rightPort)}
        self.rightAuxPort = {_FmtString(config.motors.rightAuxPort)}
        self.maxAngularRate = {_FmtFloat(config.motors.maxAngularRate)}
        self.maxDuty = {_FmtFloat(config.motors.maxDuty)}
        self.encoderCountsPerRev = {int(config.motors.encoderCountsPerRev)}
        self.forwardSign = {int(config.motors.forwardSign)}
        self.leftEncoderSign = {int(config.motors.leftEncoderSign)}
        self.rightEncoderSign = {int(config.motors.rightEncoderSign)}
        self.rightAuxEncoderSign = {int(config.motors.rightAuxEncoderSign)}


class ImuConfig:
    def __init__(self):
        self.tiltAxis = {_FmtString(config.imu.tiltAxis)}
        self.tiltSign = {int(config.imu.tiltSign)}
        self.zeroOffset = {_FmtFloat(config.imu.zeroOffset)}
        self.gyroBias = {_FmtFloat(config.imu.gyroBias)}


class EstimatorConfig:
    def __init__(self):
        self.filterType = {_FmtString(config.estimator.filterType)}
        self.alpha = {_FmtFloat(config.estimator.alpha)}
        self.loopRate = {_FmtFloat(config.estimator.loopRate)}


class ControlConfig:
    def __init__(self):
        self.loopRate = {_FmtFloat(config.control.loopRate)}
        self.maxTilt = {_FmtFloat(config.control.maxTilt)}
        self.maxTiltRate = {_FmtFloat(config.control.maxTiltRate)}
        self.maxWheelRate = {_FmtFloat(config.control.maxWheelRate)}
        self.watchdogTimeout = {_FmtFloat(config.control.watchdogTimeout)}
        self.targetTilt = {_FmtFloat(config.control.targetTilt)}


class ControllerConfig:
    def __init__(self):
        self.algorithm = {_FmtString(config.controller.algorithm)}
        self.gravityCompGain = {_FmtFloat(config.controller.gravityCompGain)}
        self.kTheta = {_FmtFloat(config.controller.kTheta)}
        self.kThetaDot = {_FmtFloat(config.controller.kThetaDot)}
        self.kPhi = {_FmtFloat(config.controller.kPhi)}
        self.kPhiDot = {_FmtFloat(config.controller.kPhiDot)}
        self.sScale = {_FmtFloat(config.controller.sScale)}
        self.thetaDeadband = {_FmtFloat(config.controller.thetaDeadband)}
        self.thetaDotDeadband = {_FmtFloat(config.controller.thetaDotDeadband)}
        self.actuatorTau = {_FmtFloat(config.controller.actuatorTau)}
        self.thetaDotFilterAlpha = {_FmtFloat(config.controller.thetaDotFilterAlpha)}
        self.innerNaturalFrequency = {_FmtFloat(config.controller.innerNaturalFrequency)}
        self.innerDampingRatio = {_FmtFloat(config.controller.innerDampingRatio)}
        self.surfaceGain = {_FmtFloat(config.controller.surfaceGain)}
        self.robustGain = {_FmtFloat(config.controller.robustGain)}
        self.boundaryLayerWidth = {_FmtFloat(config.controller.boundaryLayerWidth)}
        self.outerPositionGain = {_FmtFloat(config.controller.outerPositionGain)}
        self.outerVelocityGain = {_FmtFloat(config.controller.outerVelocityGain)}
        self.maxReferenceTiltOffset = {_FmtFloat(config.controller.maxReferenceTiltOffset)}
        self.pidKp = {_FmtFloat(config.controller.pidKp)}
        self.pidKi = {_FmtFloat(config.controller.pidKi)}
        self.pidKd = {_FmtFloat(config.controller.pidKd)}
        self.pidKs = {_FmtFloat(config.controller.pidKs)}
        self.pidIntegralStep = {_FmtFloat(config.controller.pidIntegralStep)}
        self.pidIntegralLimit = {_FmtFloat(config.controller.pidIntegralLimit)}
        self.pidPositionTargetDeg = {_FmtFloat(config.controller.pidPositionTargetDeg)}


class DriveConfig:
    def __init__(self):
        self.loopPeriodMs = {int(config.drive.loopPeriodMs)}
        self.printEveryN = {int(config.drive.printEveryN)}
        self.stopDurationMs = {int(config.drive.stopDurationMs)}
        self.driveDurationMs = {int(config.drive.driveDurationMs)}
        self.testSpeed = {_FmtFloat(config.drive.testSpeed)}
        self.maxTiltForMotion = {_FmtFloat(config.drive.maxTiltForMotion)}


class LoggingConfig:
    def __init__(self):
        self.enabled = {bool(config.logging.enabled)}
        self.level = {_FmtString(config.logging.level)}
        self.bufferSize = {int(config.logging.bufferSize)}


class RobotConfig:
    def __init__(self):
        self.name = {_FmtString(config.name)}
        self.description = {_FmtString(config.description)}
        self.chassis = ChassisConfig()
        self.motors = MotorsConfig()
        self.imu = ImuConfig()
        self.estimator = EstimatorConfig()
        self.control = ControlConfig()
        self.controller = ControllerConfig()
        self.drive = DriveConfig()
        self.logging = LoggingConfig()


def DefaultConfig():
    return RobotConfig()
'''


def GenerateHubDriveSmokeRuntime(
    config_path: Path | None = None,
    output_path: Path = DEFAULT_OUTPUT_PATH,
) -> Path:
    from LegoBalance.RobotConfig import DEFAULT_CONFIG_PATH, LoadConfig

    source_path = DEFAULT_CONFIG_PATH if config_path is None else Path(config_path)
    config = LoadConfig(path=source_path, applyLocalOverride=False)
    content = RenderHubDriveSmokeRuntime(config, source_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
        return output_path
    output_path.write_text(content, encoding="utf-8")
    return output_path


def ParseArgs() -> argparse.Namespace:
    from LegoBalance.RobotConfig import DEFAULT_CONFIG_PATH

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_PATH,
        help="YAML config to convert; defaults to configs/Default.yaml",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="generated MicroPython-safe module path",
    )
    return parser.parse_args()


def Main() -> int:
    args = ParseArgs()
    output_path = GenerateHubDriveSmokeRuntime(args.config, args.output)
    print(f"Generated {_Relative(output_path)} from {_Relative(args.config)}")
    print("Hub package runtime now follows the YAML values directly.")
    return 0


if __name__ == "__main__":
    raise SystemExit(Main())
