"""Generate the hub-safe drive-smoke config from configs/Default.yaml.

The SPIKE hub cannot parse YAML, so the package-backed hub smoke test imports
``LegoBalance.HubDriveSmokeRuntime`` instead. This script keeps that tiny
MicroPython-safe config module generated from the real desktop config and
checks the hardware-verified drive-smoke constants before upload.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

DEFAULT_OUTPUT_PATH = SRC_ROOT / "LegoBalance" / "HubDriveSmokeRuntime.py"


def _Relative(path: Path) -> Path:
    try:
        return path.relative_to(REPO_ROOT)
    except ValueError:
        return path


def _FmtString(value: str) -> str:
    return repr(str(value))


def _FmtFloat(value: float) -> str:
    return repr(float(value))


def _CheckEqual(name: str, actual: object, expected: object) -> None:
    if actual != expected:
        raise ValueError(
            f"{name} in configs/Default.yaml is {actual!r}, expected {expected!r} "
            "from the verified hub/HubDriveSmoke.py hardware smoke."
        )


def _CheckApprox(name: str, actual: float, expected: float, tolerance: float = 1e-6) -> None:
    if abs(actual - expected) > tolerance:
        raise ValueError(
            f"{name} in configs/Default.yaml is {actual!r}, expected {expected!r} "
            "from the verified hub/HubDriveSmoke.py hardware smoke."
        )


def ValidateAgainstVerifiedDriveSmoke(config) -> None:
    """Fail if Default.yaml no longer matches the hardware-verified smoke test."""
    from LegoBalance.Units import RadToDeg

    _CheckEqual("motors.leftPort", config.motors.leftPort, "B")
    _CheckEqual("motors.rightPort", config.motors.rightPort, "A")
    _CheckEqual("motors.forwardSign", config.motors.forwardSign, -1)
    _CheckEqual("motors.leftEncoderSign", config.motors.leftEncoderSign, 1)
    _CheckEqual("motors.rightEncoderSign", config.motors.rightEncoderSign, -1)
    _CheckApprox("motors.maxAngularRate", RadToDeg(config.motors.maxAngularRate), 1000.0)
    _CheckEqual("imu.tiltAxis", config.imu.tiltAxis, "pitch")
    _CheckEqual("imu.tiltSign", config.imu.tiltSign, -1)
    _CheckApprox("imu.zeroOffset", RadToDeg(config.imu.zeroOffset), -60.0)
    _CheckApprox("imu.gyroBias", RadToDeg(config.imu.gyroBias), 0.0)
    _CheckApprox("control.maxWheelRate", RadToDeg(config.control.maxWheelRate), 1000.0)
    _CheckApprox("drive.testSpeed", RadToDeg(config.drive.testSpeed), 1000.0)
    _CheckApprox("drive.maxTiltForMotion", RadToDeg(config.drive.maxTiltForMotion), 50.0)


def RenderHubDriveSmokeRuntime(config, config_path: Path) -> str:
    relative_config = _Relative(config_path)
    return f'''"""Hub-safe defaults generated from {relative_config}.

Do not edit this file by hand. Regenerate it with:

    python scripts/GenerateHubDriveSmokeRuntime.py

The real estimator, controller, safety monitor, state, and unit conversions
come from the normal ``LegoBalance`` modules. This module only carries a
small Pybricks-friendly config object because the hub cannot parse YAML.
"""


class ChassisConfig:
    def __init__(self):
        self.wheelRadius = {_FmtFloat(config.chassis.wheelRadius)}
        self.wheelBase = {_FmtFloat(config.chassis.wheelBase)}
        self.bodyMass = {_FmtFloat(config.chassis.bodyMass)}
        self.bodyHeightCoM = {_FmtFloat(config.chassis.bodyHeightCoM)}
        self.bodyInertia = {_FmtFloat(config.chassis.bodyInertia)}


class MotorsConfig:
    def __init__(self):
        self.leftPort = {_FmtString(config.motors.leftPort)}
        self.rightPort = {_FmtString(config.motors.rightPort)}
        self.maxAngularRate = {_FmtFloat(config.motors.maxAngularRate)}
        self.maxDuty = {_FmtFloat(config.motors.maxDuty)}
        self.encoderCountsPerRev = {int(config.motors.encoderCountsPerRev)}
        self.forwardSign = {int(config.motors.forwardSign)}
        self.leftEncoderSign = {int(config.motors.leftEncoderSign)}
        self.rightEncoderSign = {int(config.motors.rightEncoderSign)}


class ImuConfig:
    def __init__(self):
        self.tiltAxis = {_FmtString(config.imu.tiltAxis)}
        self.tiltSign = {int(config.imu.tiltSign)}
        self.zeroOffset = {_FmtFloat(config.imu.zeroOffset)}
        self.gyroBias = {_FmtFloat(config.imu.gyroBias)}


class EstimatorConfig:
    def __init__(self):
        self.filterType = {_FmtString(config.estimator.filterType)}
        self.alpha = {_FmtFloat(config.estimator.alpha)}
        self.loopRate = {_FmtFloat(config.estimator.loopRate)}


class ControlConfig:
    def __init__(self):
        self.loopRate = {_FmtFloat(config.control.loopRate)}
        self.maxTilt = {_FmtFloat(config.control.maxTilt)}
        self.maxTiltRate = {_FmtFloat(config.control.maxTiltRate)}
        self.maxWheelRate = {_FmtFloat(config.control.maxWheelRate)}
        self.watchdogTimeout = {_FmtFloat(config.control.watchdogTimeout)}


class DriveConfig:
    def __init__(self):
        self.testSpeed = {_FmtFloat(config.drive.testSpeed)}
        self.maxTiltForMotion = {_FmtFloat(config.drive.maxTiltForMotion)}


class LoggingConfig:
    def __init__(self):
        self.enabled = {bool(config.logging.enabled)}
        self.level = {_FmtString(config.logging.level)}
        self.bufferSize = {int(config.logging.bufferSize)}


class RobotConfig:
    def __init__(self):
        self.name = {_FmtString(config.name)}
        self.description = {_FmtString(config.description)}
        self.chassis = ChassisConfig()
        self.motors = MotorsConfig()
        self.imu = ImuConfig()
        self.estimator = EstimatorConfig()
        self.control = ControlConfig()
        self.drive = DriveConfig()
        self.logging = LoggingConfig()


def DefaultConfig():
    return RobotConfig()
'''


def GenerateHubDriveSmokeRuntime(
    config_path: Path | None = None,
    output_path: Path = DEFAULT_OUTPUT_PATH,
) -> Path:
    from LegoBalance.RobotConfig import DEFAULT_CONFIG_PATH, LoadConfig

    source_path = DEFAULT_CONFIG_PATH if config_path is None else Path(config_path)
    config = LoadConfig(path=source_path, applyLocalOverride=False)
    ValidateAgainstVerifiedDriveSmoke(config)
    content = RenderHubDriveSmokeRuntime(config, source_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
        return output_path
    output_path.write_text(content, encoding="utf-8")
    return output_path


def ParseArgs() -> argparse.Namespace:
    from LegoBalance.RobotConfig import DEFAULT_CONFIG_PATH

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG_PATH,
        help="YAML config to convert; defaults to configs/Default.yaml",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="generated MicroPython-safe module path",
    )
    return parser.parse_args()


def Main() -> int:
    args = ParseArgs()
    output_path = GenerateHubDriveSmokeRuntime(args.config, args.output)
    print(f"Generated {_Relative(output_path)} from {_Relative(args.config)}")
    print("Verified config matches hub/HubDriveSmoke.py hardware smoke constants.")
    return 0


if __name__ == "__main__":
    raise SystemExit(Main())
